name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ دریافت کد از GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ فعال‌سازی SSH با کلید خصوصی ذخیره‌شده در Secrets
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3️⃣ اجرای دستورات روی سرور
      - name: Deploy to Server
        run: |
          echo "Deploy started on server..."
          ssh -o StrictHostKeyChecking=no root@171.22.26.38 '
            cd /opt/Havirkesht
            git pull origin main
            docker compose down
            docker compose up -d --build
          '
          echo "Deploy finished successfully!"
